### ISSUE TITLE
Problems with Database Connections

### ISSUE THREAD

**Issue by Brandst2022** [jepiqueau/jeep-sqlite#11] opened 2022-06-02 14:49 UTC
Hello,
sometimes we have the problem that a database connections failed.
Also I close the database or open it again - I get the same problem.

What are my mistakes?
I test it on chrome.

Thx Thomas

var queryDB = async function (sql) {
	 		        await customElements.whenDefined('jeep-sqlite');
    			        const jeepSqlite = document.querySelector('jeep-sqlite');
    			        if(await jeepSqlite.isStoreOpen()) {
    				        await jeepSqlite.createConnection({
                                              database:dbName,
                                              version: 1
                                  });
    			};
    			await jeepSqlite.open({database: dbName});
    			let isDB = await jeepSqlite.isDBOpen({database:dbName})
    			if (!isDB.result) return Promise.reject(new Error("isDB failed"));
	    		
	try {
		let r = await jeepSqlite.query({database: dbName, statement: sql});
		//await jeepSqlite.closeConnection({database:dbName});
		//await jeepSqlite.close({database: dbName});
		
		return r;
	} catch(e){
		localError("ERROR", "ERROR", sql, "1", "1", e);
	}
};

**Comment by Brandst2022** [comment] 2022-06-02 16:03
![Screenshot 2022-06-02 180255](https://user-images.githubusercontent.com/106758375/171674275-de0ea0ae-90bc-43c6-9f61-425b463b4b93.png)

Sometimes I get the message and sometimes not - why?

**Comment by Brandst2022** [comment] 2022-06-02 16:07
![Screenshot 2022-06-02 180717](https://user-images.githubusercontent.com/106758375/171675004-5d993cf4-f568-4f3f-9cf8-0f5d96fee861.png)
And sometimes it works without problems

**Comment by jepiqueau** [comment] 2022-06-02 16:12
@Brandst2022 which framework are you using?

**Comment by Brandst2022** [comment] 2022-06-02 16:14
> @Brandst2022 which framework are you using?

In this example Dojo; But also without a framework with plain Javascript and HTML

**Comment by Brandst2022** [comment] 2022-06-03 06:42
Now I try to destroy the object and create a new connection. Without success;
The strange thing is that it happens only sometimes - not always
Any ideas?
Thx Thomas

**Comment by jepiqueau** [comment] 2022-06-04 05:25
@Brandst2022 look at examples where chechConnectionsConsistency and is Connection to create or retrieve a connection capacitor- solid-app on my github

**Comment by Brandst2022** [comment] 2022-06-20 12:39
I've done this. I checked checkConnectionsConsistency and isConnection to create or retrieve a connection.
Always the same result.
I use version 1.5.2 and the message I get is: "database xxxxSQLite.db is not opened". This is a message from your code.
If no connection is availabe I try:
await jeepSqlite.open({database: dbName});
without a success.

This problem I have found only at safari.
Do you know this?

**Comment by jepiqueau** [comment] 2022-06-20 17:28
@Brandst2022 can you share your code?

**Comment by Brandst2022** [comment] 2022-06-21 06:08
Hi, I've attached the code.
openDBNew is sometimes my problem.
[code.pdf](https://github.com/jepiqueau/jeep-sqlite/files/8946229/code.pdf)

**Comment by Brandst2022** [comment] 2022-06-28 16:50
So, now I can reproduce the problem. If a do a lot of database request I lose the db connection.
There is no chance to get the database again with version 1.5.3.

I tried this to get a new db connection:

	await customElements.whenDefined('jeep-sqlite');
	         		var db = document.querySelector('jeep-sqlite');
	         		
	         		await db.createConnection({
                      database:dbName,
                      version: 1
                  	});
	            	
	         		
                                await db.open({database:dbName});	


I have no chance to get the database on safari on a ipad.

Do you have any ideas?

**Comment by jepiqueau** [comment] 2022-06-29 05:45
@Brandst2022 do not forget that on web the database is kept in memory even when you store it so you have so many tables and data in that it may be a memory issue i have no idea

**Comment by Brandst2022** [comment] 2022-06-29 14:46
I've no problems with the data. There are about 50.000 records available.
The problem is only I do a lot of clicks.
In my test cases I never store it back. Do you know a possibility to remove it from memory?
Maybe you have on idea more.
Thx Thomas

**Comment by jepiqueau** [comment] 2022-06-29 18:37
@Brandst2022 sql.js use the database in memory  so there is no way to remove it from the memory. No i do not have any idea on what is going on i never see that during my tests. Sorry

**Comment by Brandst2022** [comment] 2022-07-06 07:38
Many thanks for your response.
Maybe there is a memory leak in the sql.js
Is it possible to implement a new version of sql.js in your framework?

**Comment by jepiqueau** [comment] 2022-07-06 09:22
@Brandst2022 for the time being you have to stick to 1.6.2 it seems on the 1.7.x they have make some changes that i need to test first.

**Comment by Brandst2022** [comment] 2022-07-08 05:57
thx for your fast response.
One another idea. What have I seen. The ArrayBuffer is the challenge. I have a global variable and I will delete the content.
Is there a possibility. Don't delete the data in das database but I will remove it from the memory.
To set the variable to "null" doesn't work.
But the ideas is to open the ArrayBuffer and replace the values with null.
Thx Thomas

**Comment by jepiqueau** [comment] 2022-07-08 08:02
@Brandst2022 try the dev version i published yesterday with sql.js@1.7.0

**Comment by jepiqueau** [comment] 2022-07-08 08:04
@Brandst2022 jeep-sqlite@1.5.4-dev2

**Comment by Brandst2022** [comment] 2022-07-08 13:12
thx - I'll test it with the new version.
Thomas

**Comment by Brandst2022** [comment] 2022-07-12 05:46
Hi, since friday with the new version we don't have problems.
We do some more tests this week but the problems with lost database connections are solved.
Thank you for your great support.
Thomas

**Comment by jepiqueau** [comment] 2022-07-12 06:20
@Brandst2022 i am happy of this have a great app development after some more tests if it is okay feel free to close the issue

**Comment by Brandst2022** [comment] 2022-07-13 11:52
Not good. Today the same error again.

**Comment by jepiqueau** [comment] 2022-07-13 16:09
@Brandst2022 share your app on github i may have a look when i have time

**Comment by Brandst2022** [comment] 2022-07-14 05:55
I've found the reason for this.
I don't have a single page application.
In the application I switch to another website and on every website a connection will created.
In the background the arraybuffer is growing.
In Chrome there is no problem; After switching the website the Arraybuffer in the memory is removed.
In Safari the Arraybuffer is also available.
So I reopen the website I have to register the element again and this is my problem.

My question: Is there a possibility to remove the arraybuffer? I've an event for this.
Thx Thomas
![Screenshot 2022-07-14 075306](https://user-images.githubusercontent.com/106758375/178910123-9ecfc87f-3434-43a2-ba15-69803fe8bfce.png)

**Comment by jepiqueau** [comment] 2022-07-14 07:39
@Brandst2022 may be you can try to close the connection and delete the jeep-sqlite element when you leave a web-site and recreate a New jeep-sqlite element and then open the store and create  a new connection 
 when you open a new web-site this will certainly (to be tested) suppress the arrayBuffer.

**Comment by Brandst2022** [comment] 2022-07-14 08:06
I tried this:
jeepSQLite.closeConnection() but the variable jeepSQLite is global on the website.
With or wihtout closeConnection is no difference. The arraybuffer is available.
But is there a possiblity to get the arraybuffer and remove the childs?

**Comment by Brandst2022** [comment] 2022-07-15 11:17
Hi, one question more.
In sql.js there are functions "freemem". Is it possibile to use this with your source?
Thx Thomas

**Comment by jepiqueau** [comment] 2022-07-15 12:55
@Brandst2022 i never use the class Statement in the jeep-sqlite Stencil component. If i understand well from the doc the free or freemem functions are only defined for that class.

**Comment by jepiqueau** [comment] 2022-07-15 13:09
@Brandst2022 I do not really understand your app as you said that each new page is calling a new web site meaning that if you create the html element jeep-sqlite for each page and remove it when you leave the page the jeepSQLite is not global but defined at the page level. The problem appears only on Safari not on Google ?

**Comment by Brandst2022** [comment] 2022-07-16 06:31
Absolut correct.
And it appears only on Safari.
If I do about 100 times jeepSQLite.open in a short time on chrome I've the
possibility to reload the site and it works - not so on Safari.

Now I close the connection and remove the jeepSQLite on the webpage
(jeepSQLite.remove()) if I switch to a new page.
At the moment I will do the tests.

**Comment by Brandst2022** [comment] 2022-07-19 06:21
Good morning,
the test was not successful.
One another question: what is the difference between .close and .closeConnection
Could this be a solutions for this?

Thx Thomas

**Comment by jepiqueau** [comment] 2022-07-19 07:51
@Brandst2022 closeConnection remove the database connection from memory before to remove the connection closeConnection close the database. 
Close close the database but leave the connection opened so you can reuse it later you will have to do a db.open first

**Comment by Brandst2022** [comment] 2022-07-19 08:05
Thx - could be this a problem.
I have never used the function "close". Only closeConnection.
Is this a problem if i will do "often" db.open and the database is never closed - only the database connection?

**Comment by jepiqueau** [comment] 2022-07-19 08:09
@Brandst2022 the closeConnection do a db.close(). So this is not the problem

**Comment by Brandst2022** [comment] 2022-07-19 12:11
What I've found out:
On Safari: If I do "closeConnection" or "close" we get very often the problem that the database cannot open again.
Example: 
- Open a webpage
- open a database connection for this web page
- close a database connection after transaction (closeConnection)
- open a database connection for this web page
- close a database connection after transcation (closeConnection).
- ....
- I switch to a new webpage
- open a database connection for this web page
- close a database connection after transaction (closeConnection)
...
And then I get an error: cannot opened the database

If I remove "closeConnection" or "close" it works much more better.
Is there a limitation?
I don't know!

**Comment by jepiqueau** [comment] 2022-07-19 15:04
@Brandst2022 my advise will be nor to close the connection neither the db after each transaction. You may do it when you move to a new web page and reopen it  when you enter the new page but even this should not be required.

**Comment by jepiqueau** [comment] 2022-07-19 15:24
@Brandst2022  you may create a function like this that you call on each page when the page initialize
```
      export const openConnection = async (dbName, encrypted, mode, version,
                                    isDelete) => {
        try {
          const retCC  = (await jeepSqlite.checkConnectionsConsistency({dbNames:[dbName]})).result;
          const isConn = (await jeepSqlite.isConnection({database: dbName})).result;
          if(retCC && isConn) {
              await jeepSqlite.retrieveConnection({database: dbName});
          } else {
              await jeepSqlite.createConnection({database: dbName, encrypted: encrypted, mode: mode,
                                                 version: version});
          }
          if (isDelete) {
                await deleteDatabase(dbName);
          }
          await jeepSqlite.open({database: dbName});
          return Promise.resolve();
        } catch (err) {
            return Promise.reject(err);
        }
      }
      export const deleteDatabase = async (dbName) => {
        try {
            const ret = (await jeepSqlite.isDBExists({database: dbName})).result;
            if(ret) {
                await jeepSqlite.deleteDatabase({database: dbName});
                return Promise.resolve();
            } else {
                return Promise.resolve();
            }
        } catch(err) {
            return Promise.reject(err);
        }
      }
```

**Comment by Brandst2022** [comment] 2022-07-19 18:25
thx for the code.
In which file I can find: the function "retrieveConnection"?
jeep-sqlite.js?

**Comment by jepiqueau** [comment] 2022-07-20 06:28
@Brandst2022 sorry i thought it was implemented in jeep-sqlite i missed that one i will have to implement it. I am in the middle of the development of delete with composite Keys and composite Foreign Keys so i need a bit of time before adding this method. Sorry for the delay

**Comment by jepiqueau** [comment] 2022-07-20 07:30
@Brandst2022 Discard my answer, the retrieveConnection method is in the `SQLiteConnection` class of the `@capacitor-community/sqlite` plugin and not in the `jeep-sqlite` component. So if you are using the `jeep-sqlite` component alone you do not have access to that method. So this should work:

```
      export const openConnection = async (dbName, encrypted, mode, version,
                                    isDelete) => {
        try {
          await jeepSqlite.checkConnectionsConsistency({dbNames:[dbName]});
          await jeepSqlite.createConnection({database: dbName, encrypted: encrypted, mode: mode,
                                                 version: version});
          if (isDelete) {
                await deleteDatabase(dbName);
          }
          await jeepSqlite.open({database: dbName});
          return Promise.resolve();
        } catch (err) {
            return Promise.reject(err);
        }
      }

```

**Comment by jepiqueau** [comment] 2022-07-22 06:58
@Brandst2022 Did that solve the issue?

**Comment by Brandst2022** [comment] 2022-07-22 10:53
No sorry

Von meinem iPhone gesendet

**Comment by jepiqueau** [comment] 2022-08-11 16:26
@Brandst2022 i come back on this. In release 1.5.5 i have added tests `index_page1_issue11.html` & `index_page2_issue11.html` to try reproducing the issue but unfortunately it works fine so i am not able to reproduce your issue. 
the `Page 1 Issue11 Tests Page` should be run first it creates the database and fill the user you can modify the following parameters 
- `nUser` : number of users created 
-  `withConn` true will open and close the connection for each transaction, false will open once and close the connection at the end of the process

I tested on Safari for 10000 users with withConn = true it took 673s  and with withConn = false 107s.
I also tested on Chrome with withConn = false it took 527s so i did not test with witConn = true

When you have run `Page 1 Issue11 Tests Page` you can now run `Page 2 Issue11 Tests Page` which is just querying the users table and compare the number of users returned and the parameter `nUser`

i think you should look at the code and compare with your code. in case you cannot fix it in your code modify my code till you reproduce the error
i cannot do more than this.

**Comment by Brandst2022** [comment] 2022-08-18 08:45
Thank you for your support.
The problem is iPAD and Safari.
If the application is open (in the browser) and iPAD goes in den suspend modus and I reopen the application I can't get a database connection.
That's my problem. Do you have some ideas?

**Comment by jepiqueau** [comment] 2022-08-18 15:37
@Brandst2022 What do you mean by "den suspend mode" do you mean going in the background

**Comment by Brandst2022** [comment] 2022-08-18 15:39
correct

**Comment by Brandst2022** [comment] 2022-08-19 06:59
it depends also on the performance of a device. iPAD 4th generation we have this problems. iPAD 6th generation we don't have this problems.
I think the problem is the time / process do generate the DOM Object for the database content.
What do you think?

**Comment by jepiqueau** [comment] 2022-08-19 09:51
@Brandst2022 Do not have any idea as i do not have iPad to test it.

**Comment by jepiqueau** [comment] 2022-12-08 08:19
@Brandst2022 do you still have the issue?

**Comment by jepiqueau** [comment] 2023-03-31 11:11
@Brandst2022 No feedback so i close the issue

**Closed as completed by jepiqueau** 2023-03-31 11:11 UTC
